#+setupfile: ~/org/aux/setupfile.org

* Tech
** Screencasting
- ffcast2 via someone on arch works alright, thought it seems that ffmpeg by itself might
  work fine. ffcast2 works great by default, but without sound. After all the options
  needed to provide to ffmpeg for sound, it's unclear what advantage ffcast2
  offers. https://github.com/lolilolicon/FFcast2
- freeseer: sounds quite promising. https://github.com/fosslc/freeseer
- istanbul
- wiki comparison: http://en.wikipedia.org/wiki/Comparison_of_screencasting_software
- gtk record-my-desktop
- ffmpeg
  - ubuntu forums tutorial: http://ubuntuforums.org/showthread.php?t=1392026
  - page where I found how to sync audio: http://www.kkoncepts.net/node/69
  - another helpful walkthrough: http://forums.freebsd.org/showthread.php?t=23826
  - final command I used: =code=ffcast ffmpeg -f alsa -ac 2 -i hw:0,0 -r 32 -vcodec
    mpeg2video -sameq -async 1 test.mpeg=code=  

** IR controlled LEDs and Arduino
- Inventables: http://www.inventables.com/technologies/smart-infrared-transmitter-ctrlm
- CtrlM demo: http://www.youtube.com/watch?v=3fSsRGN1ip0
- Arduino: http://www.arduino.cc/
  
* Obconf from Larrson
# Tint2 config file
# For information on manually configuring tint2 see http://code.google.com/p/tint2/wiki/Configure
# To use this as default tint2 config: save as $HOME/.config/tint2/tint2rc

panel_items = LTSBC

# Background definitions
# ID 1
rounded = 0
border_width = 1
background_color = #000000 60
border_color = #FFFFFF 5

# ID 2
rounded = 0
border_width = 0
background_color = #000000 40
border_color = #FFFFFF 40

# ID 3
rounded = 5
border_width = 0
background_color = #000000 5
border_color = #FFFFFF 60

# Panel
panel_monitor = all
panel_position = top center horizontal
panel_size = 100% 26
panel_margin = 0 0
panel_padding = 0 0 0
panel_dock = 0
wm_menu = 0
panel_layer = normal
panel_background_id = 1

# Panel Autohide
autohide = 0
autohide_show_timeout = 0.3
autohide_hide_timeout = 2
autohide_height = 2
panel_layer = top
strut_policy = follow_size

#Launchers
#launcher_icon_theme = Faenza-Dark
#launcher_padding = 2 0 2
#launcher_background_id = 0
#launcher_icon_size = 24
#launcher_item_app = ~/.config/tint2/settings.desktop

# Taskbar
taskbar_mode = multi_desktop
taskbar_padding = 2 2 0
taskbar_background_id = 0
taskbar_active_background_id = 0

# Tasks
urgent_nb_of_blink = 5
task_icon = 0
task_text = 1
task_centered = 1
task_maximum_size = 140 35
task_padding = 10 2
task_background_id = 0
task_active_background_id = 2
task_urgent_background_id = 2
task_iconified_background_id = 3

# Task Icons
task_icon_asb = 70 0 0
task_active_icon_asb = 100 0 0
task_urgent_icon_asb = 100 0 0
task_iconified_icon_asb = 70 0 0

# Fonts
task_font = Liberation Sans 10
task_font_color = #FFFFFF 60
task_active_font_color = #FFFFFF 80
task_urgent_font_color = #FFFFFF 80
task_iconified_font_color = #FFFFFF 60
font_shadow = 0

# System Tray
systray = 1
systray_padding = 2 0 2
systray_sort = ascending
systray_background_id = 0
systray_icon_size = 24
systray_icon_asb = 70 0 0

# Clock
time1_format = %a %d %b - %H:%M
time1_font = Liberation Sans 10
clock_font_color = #FFFFFF 63
clock_padding = 6 0
clock_background_id = 0

# Tooltips
tooltip = 0
tooltip_padding = 2 2
tooltip_show_timeout = 0.7
tooltip_hide_timeout = 0.3
tooltip_background_id = 1
tooltip_font = sans 10
tooltip_font_color = #000000 80

# Mouse
mouse_middle = none
mouse_right = close
mouse_scroll_up = iconify
mouse_scroll_down = toggle

# Battery
battery = 1
battery_low_status = 15
battery_low_cmd = notify-send "battery low"
battery_hide = 98
bat1_font = Liberation Sans 8
bat2_font = sans 6
battery_font_color = #FFFFFF 63
battery_padding = 1 0
battery_background_id = 0

# End of config

* Scotch
- 60 for Aberlour
- 50 for Ardbeg 10
- 75 for Glendronach
- 47 for Compass Box (France44 had it for 37 but appears to have sold out)


| Scotch            | Chicago Lake | Syrdyks | France 44 | Haskells | Merwins |
|-------------------+--------------+---------+-----------+----------+---------|
| Aberlour A'bunadh | -            | *60*    | 70        |       63 |      69 |
| Ardbeg 10         | 50           | 50      | 50        |     *42* |      47 |
| Glendronach       | -            | -       | -         |       90 |    *75* |
| Peat Monster      | 44           | 55      | -         |       60 |      47 |

* Libary meeting rooms
** Augsburg Park
- 7100 Nicollet Ave., Richfield
- Closes Mon at 8p
- Meeting room (5-60)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=100
  - Screen, easel, podium
  - Avail: July 23 (6:30-8p)
** Edina
- 5280 Grandview Square, Edina
- Closes Mon at 8p
- Conference room (1-15)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=168
  - White board
  - Avail: July 9/23 (6:30-8p)
- Meeting room (10-75)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=111
  - Screen, white board, sink
  - Avail: June 4, July 9/23 (6:30-8p)

** Golden Valley
- 830 Winnetka Ave. N., Golden Valley
- Closes Mon at 8p
- Meetin room (10-70)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=113
  - Screen
  - Avail: July 9/23 (6:30-8p)

** Oxboro
- 8801 Portland Ave. S., Bloomington
- Closes Mon at 8p
- Meeting room (10-80)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=113
  - Tables/chairs, podium, screen
  - Avail: May 21, June 4, July 9/23 (6:30-8p)
** Penn Lake
- 8800 Penn Ave. S., Bloomington
- Closes Mon at 8p
- Meeting room (10-80)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=140
  - Table, podium, screen
  - Avail: July 9/23 (6:30-8p)
** Southdale
- 7001 York Ave. S., Edina
- Closes Mon at 9p
- Ethyl Berry (15-49)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=151
  - Screen, podium, kitchen, 13 tables
  - Avail: June 4, July 9 (6:30-9p)
- Helen Young (15-49)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=152
  - Tables, large white wall might work for projector, chairs
  - Avail: July 9
- Public conference room (3-10)
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=153
  - Central table surrounded by chairs, maybe could project on wall
  - Avail: May 21, June 4, July 9/23 (6:30-9p)
- Full meeting room (15-195)
  - *This appears to be the Ethyl Berry and Helen Young rooms combined*
  - Link: http://www.hclib.org/pub/info/meetingrooms/Details.cfm?ID=150

* PMT Script

I'm John Henderson in 3M's Automotive Aftermarket Division. Most of my life is hilarious,
but today I'd like to talk about something serious: male baldness as a result of
participating in a study for 3M Medical's prototype pre-operative shaver. This is no
laughing matter.

As an innovative engineer, however, I know there's a solution for everything. Thanks to
3M's recently launched PMT, or Automotive Precision Masking Tape if you're not into the
whole brevity thing, we're going to fix this chrome dome right up.

Thankfully, PMT utilizes a smooth Washi paper backing so we won't have to deal with any of
those unsightly built up paint edges that other tapes leave behind on bald heads. PMT also
features excellent adhesive wet out properties for low removal force. This means I
get a look that's a killer with the ladies... without killing my scalp.

Well, I think we'll get right down to it. I'm here with PMT lead developer and precision
masker, Jeff Schwab to demo the raw power and versatility of PMT.

[Starts masking]

Hey Jeff, leave me some sideburns, will you? I don't want to look like a weirdo.

[Paint]

With today's advanced paint systems, don't try and cut corners on the bake cycle.

[Hairdry/demask]

Well, there you have it. Another win for 3M's line of automotive masking solutions. Thanks for
joining us and next time you're looking for an automotive masking tape, choose PMT. It'll
really put some hair on your head.

[Show before/after screenshot]
